site_name: Arduitronics ESP Kit1
site_url: https://arduitronics.github.io/ESP-kit1/
nav:
    - Home: index.md
    - Content: content.md
    - License: license.md
    - About: about.md
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
